defaults:
  - default.yaml

net:
  _target_: src.models.components.perceiver.Perceiver
  input_channels: ${datamodule.dataset.reference_shape}         # number of channels for each token of the input
  input_axis: 1                                                 # number of axis for input data (2 for images, 3 for video)
  num_freq_bands: 6                                             # number of freq bands, with original value (2 * K + 1)
  max_freq: 10.                                                 # maximum frequency, hyperparameter depending on how fine the data is
  depth: 1                                                      # depth of net. The shape of the final attention mechanism will be:
                                                                #   depth * (cross attention -> self_per_cross_attn * self attention)
  num_latents: 1024                                             # number of latents, or induced set points, or centroids. different papers giving it different names
  latent_dim: 512                                               # latent dimension
  cross_heads: 1                                                # number of heads for cross attention. paper said 1
  latent_heads: 8                                               # number of heads for latent self attention, 8
  cross_dim_head: 512                                           # number of dimensions per cross attention head
  latent_dim_head: 64                                           # number of dimensions per latent self attention head
  n_classes: ${datamodule.dataset.num_classes}                  # output number of classes
  attn_dropout: 0.2
  ff_dropout: 0.2
  weight_tie_layers: true                                       # whether to weight tie layers (optional, as indicated in the diagram)
  fourier_encode_data: false                                    # whether to auto-fourier encode the data, using the input_axis given. defaults to True, but can be turned off if you are fourier encoding the data yourself
  self_per_cross_attn: 1
  latent_bounds: 2
  scale: null

name: perceiver

optimizer:
  opt: lookahead_radam
  lr: 0.0002
  opt_eps: null 
  opt_betas: null
  momentum: null 
  weight_decay: 0.00001
  
illustrator: ${illustrator}