# csv logger built in lightning

csv:
  _target_: pytorch_lightning.loggers.csv_logs.CSVLogger
  save_dir:  "${paths.output_dir}/${datamodule.dataset.name}_${datamodule.dataset.feature_extractor}_${model.name}"
  name: csv
  version: null
  prefix: ""
