# https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.ModelCheckpoint.html

# Save the model periodically by monitoring a quantity.
# Look at the above link for more detailed information.
prediction_writer:
  _target_: src.utils.PredictionWriter
  write_interval: "epoch"
  raw_root_dir: ${paths.raw_root_dir}
  processed_root_dir: ${paths.ukt_root_dir}
  output_dir: ${paths.log_dir}/attention_maps